[package]
name = "wamera_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
rtmp = "0.4.0"
tokio = { version = "1.29.1", features = ["full"] }
tokio-util = "0.7.8"
v4l = "0.14.0"
